repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace  # removes trailing whitespace
      - id: end-of-file-fixer   # ensures files end with a newline
      - id: check-yaml          # validates yaml files syntax
      - id: check-added-large-files  # prevents adding large files
      - id: debug-statements    # checks for debug statements

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort  # sorts imports

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black  # formats code
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8  # checks code style
        additional_dependencies: [flake8-docstrings]
