services:
  web:
    container_name: visa_doctors_web
    restart: always
    ports:
      - "${PORT}:${PORT}"
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    env_file:
      - ./.env
    command: /start
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
          ignore:
            - 'static/'
            - 'media/'
            - '*.pyc'
            - '__pycache__/'
        - action: rebuild
          path: requirements.txt
    depends_on:
      - redis

  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./compose/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  # postgres:
  #   image: postgres:17.4-alpine
  #   restart: always
  #   env_file:
  #     - ./.env
  #   environment:
  #     POSTGRES_DB: '${SQL_NAME}'
  #     POSTGRES_USER: '${SQL_USER}'
  #     POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   ports:
  #     - "5432:5432"

volumes:
  # postgres_data:
  redis_data:
  static_volume:
  media_volume: