# Generated by Django 5.0.2 on 2025-02-25 09:19

import django.db.models.deletion
import django_ckeditor_5.fields
import shared.django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("subtitle", models.CharField(max_length=255, verbose_name="Subtitle")),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Description"),
                ),
                ("image", models.ImageField(upload_to="about/", verbose_name="Image")),
                ("experience_years", models.JSONField(verbose_name="Experience Years")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
            ],
            options={
                "verbose_name": "About",
                "verbose_name_plural": "About",
            },
            bases=(shared.django.models.TimeBaseModel, models.Model),
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Phone")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                ("telegram", models.URLField(blank=True, verbose_name="Telegram")),
                ("instagram", models.URLField(blank=True, verbose_name="Instagram")),
                ("facebook", models.URLField(blank=True, verbose_name="Facebook")),
                ("youtube", models.URLField(blank=True, verbose_name="YouTube")),
            ],
            options={
                "verbose_name": "Contact Information",
                "verbose_name_plural": "Contact Information",
            },
            bases=(shared.django.models.TimeBaseModel, models.Model),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Input"),
                            ("single", "Single Choice"),
                            ("multiple", "Multiple Choice"),
                        ],
                        default="text",
                        max_length=10,
                        verbose_name="Input Type",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["order"],
            },
            bases=(shared.django.models.TimeBaseModel, models.Model),
        ),
        migrations.CreateModel(
            name="ResultCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
            ],
            options={
                "verbose_name": "Result Category",
                "verbose_name_plural": "Result Categories",
            },
            bases=(shared.django.models.TimeBaseModel, models.Model),
        ),
        migrations.CreateModel(
            name="SurveySubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "New"), ("processed", "Processed")],
                        default="new",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Survey Submission",
                "verbose_name_plural": "Survey Submissions",
            },
            bases=(shared.django.models.TimeBaseModel, models.Model),
        ),
        migrations.CreateModel(
            name="VisaType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "icon",
                    models.ImageField(upload_to="visas/icons/", verbose_name="Icon"),
                ),
            ],
            options={
                "verbose_name": "Visa Type",
                "verbose_name_plural": "Visa Types",
            },
            bases=(shared.django.models.TimeBaseModel, models.Model),
        ),
        migrations.CreateModel(
            name="AboutHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "about",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to="app.about",
                    ),
                ),
            ],
            options={
                "verbose_name": "About Highlight",
                "verbose_name_plural": "About Highlights",
                "ordering": ["order"],
            },
            bases=(shared.django.models.TimeBaseModel, models.Model),
        ),
        migrations.CreateModel(
            name="AnswerOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("text", models.CharField(max_length=255, verbose_name="Text")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "parent_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_options",
                        to="app.answeroption",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="app.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer Option",
                "verbose_name_plural": "Answer Options",
                "ordering": ["order"],
            },
            bases=(shared.django.models.TimeBaseModel, models.Model),
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "image",
                    models.ImageField(upload_to="results/", verbose_name="Image"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="results",
                        to="app.resultcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Result",
                "verbose_name_plural": "Results",
            },
            bases=(shared.django.models.TimeBaseModel, models.Model),
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "text_answer",
                    models.TextField(blank=True, verbose_name="Text Answer"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.question"
                    ),
                ),
                (
                    "selected_options",
                    models.ManyToManyField(blank=True, to="app.answeroption"),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="app.surveysubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Response",
                "verbose_name_plural": "Responses",
            },
            bases=(shared.django.models.TimeBaseModel, models.Model),
        ),
        migrations.CreateModel(
            name="VisaDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "visa_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="app.visatype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visa Document",
                "verbose_name_plural": "Visa Documents",
                "ordering": ["order"],
            },
            bases=(shared.django.models.TimeBaseModel, models.Model),
        ),
    ]
