# Generated by Django 5.0.2 on 2025-02-25 09:42

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="about",
            options={
                "ordering": ["id"],
                "verbose_name": "About",
                "verbose_name_plural": "About",
            },
        ),
        migrations.AlterModelOptions(
            name="visatype",
            options={
                "ordering": ["id"],
                "verbose_name": "Visa Type",
                "verbose_name_plural": "Visa Types",
            },
        ),
        migrations.RemoveField(
            model_name="answeroption",
            name="parent_option",
        ),
        migrations.RemoveField(
            model_name="response",
            name="selected_options",
        ),
        migrations.RemoveField(
            model_name="response",
            name="text_answer",
        ),
        migrations.AddField(
            model_name="answeroption",
            name="level",
            field=models.PositiveIntegerField(default="1", editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="answeroption",
            name="lft",
            field=models.PositiveIntegerField(default="1", editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="answeroption",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="app.answeroption",
            ),
        ),
        migrations.AddField(
            model_name="answeroption",
            name="rght",
            field=models.PositiveIntegerField(default="1", editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="answeroption",
            name="tree_id",
            field=models.PositiveIntegerField(
                db_index=True, default="1", editable=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="response",
            name="answer",
            field=models.JSONField(default="{}", verbose_name="Answer"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="abouthighlight",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Order"
            ),
        ),
        migrations.AlterField(
            model_name="answeroption",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Order"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="input_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("single_choice", "Single Choice"),
                    ("multiple_choice", "Multiple Choice"),
                    ("date", "Date"),
                    ("file", "File"),
                ],
                default="text",
                max_length=20,
                verbose_name="Input Type",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Order"
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="app.question",
            ),
        ),
        migrations.AlterField(
            model_name="surveysubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                ],
                default="new",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="visadocument",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Order"
            ),
        ),
    ]
