# Generated by Django 5.0.2 on 2025-02-26 09:21

import app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_about_options_alter_visatype_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="experience_years",
            field=app.fields.ExperienceYearField(
                help_text='Enter years of experience and title (e.g., {"years": 28, "title": "Years of Medical Practice"})',
                verbose_name="Experience Years",
            ),
        ),
    ]
