# Generated by Django 5.0.2 on 2025-02-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_about_experience_years"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="about",
            name="image",
        ),
        migrations.RemoveField(
            model_name="abouthighlight",
            name="description",
        ),
    ]
