# Generated by Django 5.0.2 on 2025-02-26 22:35

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_about_image_remove_abouthighlight_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultcategory",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="resultcategory",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255, verbose_name="Subtitle"),
        ),
    ]
