# Generated by Django 5.0.2 on 2025-02-26 23:18

import shared.django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_resultcategory_description_resultcategory_subtitle"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniversityLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="University Name"),
                ),
                (
                    "logo",
                    models.ImageField(
                        upload_to="universities/logos/", verbose_name="Logo"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Order"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
            ],
            options={
                "verbose_name": "University Logo",
                "verbose_name_plural": "University Logos",
                "ordering": ["order"],
            },
            bases=(shared.django.models.TimeBaseModel, models.Model),
        ),
    ]
