# Generated by Django 5.0.2 on 2025-02-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_universitylogo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="description",
        ),
        migrations.AddField(
            model_name="question",
            name="placeholder",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Placeholder"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="title",
            field=models.CharField(
                default="", max_length=255, verbose_name="Question title"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="input_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("single_choice", "Single Choice"),
                    ("multiple_choice", "Multiple Choice"),
                ],
                default="text",
                max_length=20,
                verbose_name="Input Type",
            ),
        ),
    ]
