# Generated by Django 5.0.2 on 2025-02-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_question_description_question_placeholder_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="response",
            name="answer",
        ),
        migrations.AddField(
            model_name="response",
            name="selected_options",
            field=models.ManyToManyField(
                blank=True,
                related_name="responses",
                to="app.answeroption",
                verbose_name="Selected options",
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="text_answer",
            field=models.TextField(blank=True, null=True, verbose_name="Text answer"),
        ),
        migrations.AddConstraint(
            model_name="response",
            constraint=models.UniqueConstraint(
                fields=("submission", "question"), name="unique_response_per_question"
            ),
        ),
    ]
