# Generated by Django 5.0.2 on 2025-02-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_question_description_question_placeholder_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="response",
            name="answer",
        ),
        migrations.AddField(
            model_name="about",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2025-02-27 11:56:32+05:00", verbose_name="Created at"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="about",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="abouthighlight",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2025-02-27 11:56:32+05:00", verbose_name="Created at"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="abouthighlight",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="answeroption",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2025-02-27 11:56:32+05:00", verbose_name="Created at"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="answeroption",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2025-02-27 11:56:32+05:00", verbose_name="Created at"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="question",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2025-02-27 11:56:32+05:00", verbose_name="Created at"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="response",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2025-02-27 11:56:32+05:00", verbose_name="Created at"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="response",
            name="selected_options",
            field=models.ManyToManyField(
                blank=True,
                related_name="responses",
                to="app.answeroption",
                verbose_name="Selected options",
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="text_answer",
            field=models.TextField(blank=True, null=True, verbose_name="Text answer"),
        ),
        migrations.AddField(
            model_name="response",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="result",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2025-02-27 11:56:32+05:00", verbose_name="Created at"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="result",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="resultcategory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2025-02-27 11:56:32+05:00", verbose_name="Created at"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resultcategory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="surveysubmission",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2025-02-27 11:56:32+05:00", verbose_name="Created at"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="surveysubmission",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="universitylogo",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2025-02-27 11:56:32+05:00", verbose_name="Created at"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="universitylogo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="visadocument",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2025-02-27 11:56:32+05:00", verbose_name="Created at"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="visadocument",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="visatype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2025-02-27 11:56:32+05:00", verbose_name="Created at"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="visatype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddConstraint(
            model_name="response",
            constraint=models.UniqueConstraint(
                fields=("submission", "question"), name="unique_response_per_question"
            ),
        ),
    ]
