# Generated by Django 5.0.2 on 2025-02-28 22:34

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_answeroption_has_custom_input"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="description_en",
            field=django_ckeditor_5.fields.CKEditor5Field(
                null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="description_uz",
            field=django_ckeditor_5.fields.CKEditor5Field(
                null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="subtitle_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Subtitle"),
        ),
        migrations.AddField(
            model_name="about",
            name="subtitle_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Subtitle"),
        ),
        migrations.AddField(
            model_name="about",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="about",
            name="title_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="abouthighlight",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="abouthighlight",
            name="title_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="answeroption",
            name="text_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Text"),
        ),
        migrations.AddField(
            model_name="answeroption",
            name="text_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Text"),
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="address_en",
            field=models.TextField(blank=True, null=True, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="address_uz",
            field=models.TextField(blank=True, null=True, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="question",
            name="placeholder_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Placeholder"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="placeholder_uz",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Placeholder"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="title_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Question title"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="title_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Question title"
            ),
        ),
        migrations.AddField(
            model_name="resultcategory",
            name="description_en",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="resultcategory",
            name="description_uz",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="resultcategory",
            name="subtitle_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Subtitle"
            ),
        ),
        migrations.AddField(
            model_name="resultcategory",
            name="subtitle_uz",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Subtitle"
            ),
        ),
        migrations.AddField(
            model_name="resultcategory",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="resultcategory",
            name="title_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="universitylogo",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="University Name"
            ),
        ),
        migrations.AddField(
            model_name="universitylogo",
            name="name_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="University Name"
            ),
        ),
        migrations.AddField(
            model_name="visadocument",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="visadocument",
            name="description_uz",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="visatype",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="visatype",
            name="title_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
    ]
