# Generated by Django 5.0.2 on 2025-03-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_about_description_en_about_description_uz_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="response",
            name="selected_options",
            field=models.ManyToManyField(
                blank=True,
                db_index=True,
                related_name="responses",
                to="app.answeroption",
                verbose_name="Selected options",
            ),
        ),
        migrations.AlterIndexTogether(
            name="response",
            index_together={("submission", "question")},
        ),
    ]
