# Generated by Django 5.0.2 on 2025-03-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_alter_response_selected_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visadocument",
            name="description",
        ),
        migrations.RemoveField(
            model_name="visadocument",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="visadocument",
            name="description_uz",
        ),
        migrations.AddField(
            model_name="visadocument",
            name="title",
            field=models.CharField(
                default="test", max_length=255, verbose_name="Title"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="visadocument",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="visadocument",
            name="title_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
    ]
