# Generated by Django 5.0.2 on 2025-03-02 13:55

import shared.django.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_remove_visadocument_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visatype",
            name="icon",
            field=shared.django.fields.SVGImageField(
                help_text="Upload SVG icon",
                upload_to="visas/icons/",
                verbose_name="Icon",
            ),
        ),
    ]
