# Generated by Django 5.0.2 on 2025-03-02 15:45

import shared.django.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_alter_visatype_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visatype",
            name="icon",
            field=shared.django.fields.SVGFileField(
                help_text="Upload SVG icon",
                upload_to="visas/icons/",
                verbose_name="Icon",
            ),
        ),
    ]
