# Generated by Django 5.0.2 on 2025-03-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_alter_visatype_icon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visatype",
            options={
                "ordering": ["order"],
                "verbose_name": "Visa Type",
                "verbose_name_plural": "Visa Types",
            },
        ),
        migrations.AddField(
            model_name="visatype",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Order"
            ),
        ),
    ]
