# Generated by Django 5.0.2 on 2025-03-02 20:13

import app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_alter_visatype_options_visatype_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="experience_years_en",
            field=app.fields.ExperienceYearField(
                help_text='Enter years of experience and title (e.g., {"years": 28, "title": "Years of Medical Practice"})',
                null=True,
                verbose_name="Experience Years",
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="experience_years_uz",
            field=app.fields.ExperienceYearField(
                help_text='Enter years of experience and title (e.g., {"years": 28, "title": "Years of Medical Practice"})',
                null=True,
                verbose_name="Experience Years",
            ),
        ),
        migrations.AlterField(
            model_name="visadocument",
            name="title",
            field=models.TextField(verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="visadocument",
            name="title_en",
            field=models.TextField(null=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="visadocument",
            name="title_uz",
            field=models.TextField(null=True, verbose_name="Title"),
        ),
    ]
