# Generated by Django 5.0.2 on 2025-03-06 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_about_experience_years_en_about_experience_years_uz_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InputFieldType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Field Type Name"),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Field Type Name"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Field Type Name"
                    ),
                ),
                (
                    "regex_pattern",
                    models.CharField(
                        help_text="Regular expression pattern for field validation",
                        max_length=255,
                        verbose_name="Regular Expression Pattern",
                    ),
                ),
                (
                    "error_message",
                    models.CharField(
                        help_text="Error message to display when validation fails",
                        max_length=255,
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "error_message_en",
                    models.CharField(
                        help_text="Error message to display when validation fails",
                        max_length=255,
                        null=True,
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "error_message_uz",
                    models.CharField(
                        help_text="Error message to display when validation fails",
                        max_length=255,
                        null=True,
                        verbose_name="Error Message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Input Field Type",
                "verbose_name_plural": "Input Field Types",
            },
        ),
        migrations.AddField(
            model_name="answeroption",
            name="field_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Field type for validation (only applicable for options with custom input)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answer_options",
                to="app.inputfieldtype",
            ),
        ),
    ]
