# Generated by Django 5.0.2 on 2025-03-07 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_inputfieldtype_answeroption_field_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answeroption",
            name="field_type",
        ),
        migrations.RemoveField(
            model_name="inputfieldtype",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="inputfieldtype",
            name="title_uz",
        ),
        migrations.AddField(
            model_name="question",
            name="field_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Field type for validation (only applicable for text questions)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="app.inputfieldtype",
            ),
        ),
    ]
