# Generated by Django 5.0.2 on 2025-03-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_remove_answeroption_field_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inputfieldtype",
            name="title_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Field Type Name"
            ),
        ),
        migrations.AddField(
            model_name="inputfieldtype",
            name="title_uz",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Field Type Name"
            ),
        ),
    ]
