# Generated by Django 5.0.2 on 2025-03-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_inputfieldtype_title_en_inputfieldtype_title_uz"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_required",
            field=models.BooleanField(default=True, verbose_name="Is required"),
        ),
    ]
