# Generated by Django 5.0.2 on 2025-03-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_question_field_title_question_field_type_choice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="field_title",
        ),
        migrations.RemoveField(
            model_name="question",
            name="field_type_choice",
        ),
        migrations.AddField(
            model_name="inputfieldtype",
            name="field_key",
            field=models.CharField(
                blank=True,
                help_text="Short title used in exports",
                max_length=100,
                verbose_name="Field key for export",
            ),
        ),
        migrations.AddField(
            model_name="inputfieldtype",
            name="field_type_choice",
            field=models.CharField(
                choices=[("string", "String"), ("number", "Number")],
                default="string",
                help_text="Determines how this field is filtered in exports",
                max_length=20,
                verbose_name="Field type for filtering",
            ),
        ),
    ]
