# Generated by Django 5.0.2 on 2025-03-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_remove_question_field_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inputfieldtype",
            name="regex_pattern",
            field=models.CharField(
                blank=True,
                help_text="Regular expression pattern for field validation",
                max_length=255,
                verbose_name="Regular Expression Pattern",
            ),
        ),
    ]
