# Generated by Django 5.0.2 on 2025-03-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_alter_inputfieldtype_regex_pattern"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inputfieldtype",
            name="field_type_choice",
            field=models.CharField(
                choices=[
                    ("string", "String"),
                    ("number", "Number"),
                    ("choices", "Choices"),
                ],
                default="string",
                help_text="Determines how this field is filtered in exports",
                max_length=20,
                verbose_name="Field type for filtering",
            ),
        ),
    ]
