# Generated by Django 5.0.2 on 2025-03-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_alter_inputfieldtype_field_type_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="answeroption",
            name="export_field_name",
            field=models.CharField(
                blank=True,
                help_text="Short name to use in exports instead of full text",
                max_length=100,
                null=True,
                verbose_name="Export Field Name",
            ),
        ),
    ]
