# Generated by Django 5.0.2 on 2025-03-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_answeroption_export_field_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="universitylogo",
            name="url",
            field=models.URLField(
                blank=True, max_length=255, verbose_name="Website URL"
            ),
        ),
    ]
