# Generated by Django 5.0.2 on 2025-03-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_universitylogo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveysubmission",
            name="source",
            field=models.CharField(
                choices=[
                    ("website", "Website"),
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("telegram", "Telegram"),
                    ("whatsapp", "WhatsApp"),
                    ("vk", "VKontakte"),
                    ("youtube", "YouTube"),
                    ("linkedin", "LinkedIn"),
                    ("twitter", "Twitter"),
                    ("tiktok", "TikTok"),
                    ("other", "Other"),
                ],
                default="website",
                help_text="Where did the user come from?",
                max_length=20,
                verbose_name="Source",
            ),
        ),
    ]
