# Generated by Django 5.0.2 on 2025-05-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_surveysubmission_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveysubmission",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Comment about this submission",
                null=True,
                verbose_name="Comment",
            ),
        ),
    ]
