# Generated by Django 5.0.2 on 2025-05-11 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_surveysubmission_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название статуса, отображаемое пользователям",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Уникальный код для программного использования",
                        max_length=50,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Описание статуса и когда его следует использовать",
                        verbose_name="Description",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Код цвета CSS для отображения (например, #FF5733)",
                        max_length=20,
                        verbose_name="Color",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Порядок отображения статусов в списках",
                        verbose_name="Order",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Статус по умолчанию для новых заявок (только один может быть по умолчанию)",
                        verbose_name="Is Default",
                    ),
                ),
                (
                    "is_final",
                    models.BooleanField(
                        default=False,
                        help_text="Является ли этот статус финальным (заявка закрыта)",
                        verbose_name="Is Final",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Активен ли этот статус для выбора",
                        verbose_name="Active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission Status",
                "verbose_name_plural": "Submission Statuses",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="surveysubmission",
            name="status_new",
            field=models.ForeignKey(
                blank=True,
                help_text="u041du043eu0432u0430u044f u0441u0438u0441u0442u0435u043cu0430 u0441u0442u0430u0442u0443u0441u043eu0432",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                to="app.submissionstatus",
                to_field="code",
                verbose_name="Status (New)",
            ),
        ),
    ]
