# Generated by Django 5.0.2 on 2025-05-11 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_populate_submission_statuses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveysubmission",
            name="status_new",
        ),
        migrations.AlterField(
            model_name="submissionstatus",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this status is active for selection",
                verbose_name="Active",
            ),
        ),
        migrations.AlterField(
            model_name="submissionstatus",
            name="code",
            field=models.CharField(
                help_text="Unique code for programmatic usage",
                max_length=50,
                unique=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="submissionstatus",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="CSS color code for display (e.g., #FF5733)",
                max_length=20,
                verbose_name="Color",
            ),
        ),
        migrations.AlterField(
            model_name="submissionstatus",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the status and when it should be used",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="submissionstatus",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Default status for new submissions (only one can be default)",
                verbose_name="Is Default",
            ),
        ),
        migrations.AlterField(
            model_name="submissionstatus",
            name="is_final",
            field=models.BooleanField(
                default=False,
                help_text="Whether this status is final (submission is closed)",
                verbose_name="Is Final",
            ),
        ),
        migrations.AlterField(
            model_name="submissionstatus",
            name="name",
            field=models.CharField(
                help_text="Name of the status shown to users",
                max_length=100,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="submissionstatus",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Display order in status lists",
                verbose_name="Order",
            ),
        ),
        migrations.AlterField(
            model_name="surveysubmission",
            name="status",
            field=models.ForeignKey(
                help_text="Статус заявки",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                to="app.submissionstatus",
                to_field="code",
                verbose_name="Status",
            ),
        ),
    ]
