# Generated by Django 5.0.2 on 2025-05-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_migrate_status_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionstatus",
            name="name_en",
            field=models.CharField(
                help_text="Name of the status shown to users",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="submissionstatus",
            name="name_uz",
            field=models.CharField(
                help_text="Name of the status shown to users",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
    ]
