# Generated by Django 5.0.2 on 2025-05-21 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0037_submissionstatus_name_en_submissionstatus_name_uz"),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Survey title"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly name for the survey (used in frontend URLs)",
                        max_length=100,
                        unique=True,
                        verbose_name="URL Slug",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="If True, this survey will be used when no specific survey is selected",
                        verbose_name="Is default survey",
                    ),
                ),
            ],
            options={
                "verbose_name": "Survey",
                "verbose_name_plural": "Surveys",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["survey", "order"],
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="survey",
            field=models.ForeignKey(
                blank=True,
                help_text="Survey this question belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="app.survey",
                verbose_name="Survey",
            ),
        ),
        migrations.AddField(
            model_name="surveysubmission",
            name="survey",
            field=models.ForeignKey(
                blank=True,
                help_text="Survey this submission belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                to="app.survey",
                verbose_name="Survey",
            ),
        ),
    ]
