# Generated by Django 5.0.2 on 2025-05-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_survey_alter_question_options_question_survey_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="survey",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="deleted_by_cascade",
        ),
    ]
