# Generated by Django 5.0.2 on 2025-05-30 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0039_remove_survey_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="survey",
            field=models.ForeignKey(
                help_text="Survey this question belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="app.survey",
                verbose_name="Survey",
            ),
        ),
        migrations.AlterField(
            model_name="surveysubmission",
            name="survey",
            field=models.ForeignKey(
                help_text="Survey this submission belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                to="app.survey",
                verbose_name="Survey",
            ),
        ),
    ]
