# Generated by Django 5.0.2 on 2025-06-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0040_remove_survey_null_constraint"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="survey",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="unique_default_survey",
                violation_error_message="Default survey already exists!",
            ),
        ),
    ]
