# Generated by Django 5.0.2 on 2025-06-08 15:14

from django.db import migrations, models


def apply_default_topic_id(apps, schema_editor):
    Survey = apps.get_model('app', 'Survey')
    Survey.objects.filter(telegram_topic_id__isnull=True).update(telegram_topic_id=1)


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0041_survey_unique_default_survey"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="telegram_topic_id",
            field=models.IntegerField(
                blank=True,
                help_text="The ID of the Telegram topic associated with this survey.",
                null=True,
                verbose_name="Telegram Topic ID",
            ),
        ),
        migrations.RunPython(apply_default_topic_id),
    ]
