# Generated by Django 5.0.2 on 2025-06-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0042_survey_telegram_topic_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="telegram_topic_id",
            field=models.IntegerField(
                help_text="The ID of the Telegram topic associated with this survey.",
                verbose_name="Telegram Topic ID",
            ),
        ),
    ]
