# Generated by Django 5.0.2 on 2025-06-12 16:12

import app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0043_alter_survey_telegram_topic_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="front_content",
            field=app.fields.FrontContentField(
                blank=True,
                default=dict,
                help_text='JSON object with "front_title" and "front_subtitle". Use &lt;span&gt; for styling.',
                null=True,
                verbose_name="Frontend Content",
            ),
        ),
    ]
