name: CI/CD Pipeline

on:
  push:
    branches: ['master', 'development']
  pull_request:
    branches: ['master', 'development']

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test
        env:
          DJANGO_SETTINGS_MODULE: root.settings

  deploy:
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/development')
    runs-on: self-hosted
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e  # Exit on error
            
            # Function to retry commands
            function retry {
              local retries=3
              local count=0
              until "$@"; do
                exit=$?
                count=$(($count + 1))
                if [ $count -lt $retries ]; then
                  echo "Command failed. Attempt $count/$retries. Retrying in 5 seconds..."
                  sleep 5
                else
                  echo "Command failed after $retries attempts."
                  return $exit
                fi
              done
              return 0
            }
            
            echo "DEPLOY STARTED"
            cd ${{ secrets.APP_DIRECTORY }}
            
            # Pull latest changes with retry
            echo "Pulling latest changes..."
            retry git pull origin ${GITHUB_REF#refs/heads/}
            
            # Activate virtual environment and install dependencies
            echo "Installing dependencies..."
            retry source venv/bin/activate
            retry pip install -r requirements.txt
            
            # Run migrations
            echo "Running migrations..."
            python manage.py migrate --noinput
            
            # Collect static files
            echo "Collecting static files..."
            python manage.py collectstatic --noinput
            
            # Restart services
            echo "Restarting services..."
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
            
            echo "DEPLOY FINISHED"
