name: CI/CD Pipeline

on:
  push:
    branches: [ 'master', 'development' ]
  pull_request:
    branches: [ 'master', 'development' ]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Create env file
        run: |
          cat << EOF > .env
          DEBUG=True
          PORT=8000
          SECRET_KEY='django-insecure-test-key'
          TEMPLATE_APP_DIR=True
          
          CORS_ALLOWED_ORIGINS=http://localhost:3000
          CORS_ALLOW_CREDENTIALS=True
          
          SQL_ENGINE=django.db.backends.postgresql_psycopg2
          SQL_HOST=postgres
          SQL_NAME=test_db
          SQL_PORT=5432
          SQL_USER=postgres
          POSTGRES_PASSWORD=postgres
          
          ALLOWED_HOSTS=localhost,127.0.0.1
          EOF

      - name: Build and run tests
        run: |
          docker compose build web
          docker compose run --rm web python manage.py test

  deploy:
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/development')
    runs-on: self-hosted
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e  # Exit on error
            
            # Function to retry commands
            function retry {
              local retries=3
              local count=0
              until "$@"; do
                exit=$?
                count=$(($count + 1))
                if [ $count -lt $retries ]; then
                  echo "Command failed. Attempt $count/$retries. Retrying in 5 seconds..."
                  sleep 5
                else
                  echo "Command failed after $retries attempts."
                  return $exit
                fi
              done
              return 0
            }
            
            echo "DEPLOY STARTED"
            cd ${{ secrets.APP_DIRECTORY }}
            
            # Pull latest changes with retry
            echo "Pulling latest changes..."
            retry git pull origin ${GITHUB_REF#refs/heads/}
            
            # Build and start containers
            echo "Building and starting containers..."
            retry docker compose build web
            retry docker compose up -d
            
            # Run migrations
            echo "Running migrations..."
            retry docker compose exec -T web python manage.py migrate --noinput
            
            # Collect static files
            echo "Collecting static files..."
            retry docker compose exec -T web python manage.py collectstatic --noinput
            
            echo "DEPLOY FINISHED"
